set nocompatible
set showmatch
set ignorecase
set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=2
set autoindent
set number
set wildmode=longest,list
syntax on
set mouse=a
set cursorline
set ttyfast
