context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "UMC Microphone"
      capture.props = {
        node.name = "capture.UMC_Mic"
        audio.position = [ AUX0 ]
        stream.dont-remix = true
        target.object = "alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-input"
        node.passive = true
      }
      playback.props = {
        node.name = "UMC_Mic"
        media.class = "Audio/Source"
        audio.position = [ MONO ]
      }
    }
  }
  {
    name = libpipewire-module-loopback
    args = {
       node.description = "UMC Guitar"
       capture.props = {
         node.name = "capture.UMC_Guitar"
         audio.position = [ AUX1 ]
         stream.dont-remix = true
         target.object = "alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-input"
         node.passive = true
       }
       playback.props = {
         node.name = "UMC_Guitar"
         media.class = "Audio/Source"
         audio.position = [ MONO ]
       }
    }
  }
]
