hl.on("hyprland.start", function()
    hl.exec_cmd('sleep 3; ddcutil setvcp 10 "$(cat /home/vinso/.config/last_brightness)"')
    hl.exec_cmd("waybar")
    hl.exec_cmd("fooyin")
    hl.exec_cmd("zen-beta")
    hl.exec_cmd("discord --start-minimized")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd("Throne")
end)
